version: '3.1'

services:

  telegrambot-db:
    image: mysql:5.7
    restart: always
    container_name: dev-telegrambot-db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'dev_telegram_db'
      MYSQL_USER: 'babyan'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'

